### PR TITLE
.DS-Store should be ignored, for Mac OS X development

### PR DESCRIPTION
**Pull request by boristian**
Added .DS_Store to .gitinore file.

### CODE REVIEW

**Comment by Agamennon** [comment]
Thanks but that should not be there, will remove .idea from source control

**Comment by boristian** [comment]
I meant not only in the `.idea`folder, but for the whole repo `.DS_Store` should be ignored.

**Comment by Agamennon** [comment]
Thanks!

**Comment by boristian** [comment]
No problem, thank you for sharing your work. I like the idea of this module.

**Comment by Agamennon** [comment]
I think it was an idea worthy of implementing, i hope you like it, please send feedback!

**Comment by dbrans** [comment]
OS and IDE specific gitignores should live in your personal [global gitignore](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore). Otherwise you'll have everyone's IDE-OS specific gitignores in this repo.

**Pull request merged**
